### PR TITLE
Prep Mac app for release, fix bugs in iOS app

### LINKED ISSUE #248: Upgrade Sparkle to 2.4.1 to address warnings in Xcode 14.3
A change in Xcode 14.3 logs 38 warnings when building the app, all from the Sparkle framework we use to update the Mac app. It's resolved in v2.4.1; we're currently using v2.3.1 in the project.

More info here: https://github.com/sparkle-project/Sparkle/issues/2355

### PR DESCRIPTION
**Pull request by AngeloStavrow**
This PR closes #248 and #256, and makes progress towards #224.

To prepare for the release of the Mac app, we get some dependencies upgraded for Sparkle (as well as docs for updating the app), and set up a new WFNavigation view that begins to incorporate SwiftUI's newer navigation paradigms into the Mac app. Some work has been done around the iOS app but it's a bit trickier to manage.

This PR also fixes a bug that would force the app to navigate back to the post list whenever you'd switch over to another app.

### CODE REVIEW

File: Shared/Extensions/WriteFreelyModel+API.swift [hunk 1]
```diff
@@ -94,9 +94,16 @@ extension WriteFreelyModel {
         }
 
         if post.language == nil {
-            if let languageCode = Locale.current.languageCode {
-                post.language = languageCode
-                post.rtl = Locale.characterDirection(forLanguage: languageCode) == .rightToLeft
```
Comment (AngeloStavrow) [inline Shared/Extensions/WriteFreelyModel+API.swift:99]: This code was throwing warnings in newer versions of Xcode.

File: Shared/Navigation/ContentView.swift [hunk 2]
```diff
@@ -5,62 +5,86 @@ struct ContentView: View {
...
-            #if os(macOS)
-            CollectionListView()
-                .withErrorHandling()
-                .toolbar {
-                    Button(
-                        action: {
-                            NSApp.keyWindow?.contentViewController?.tryToPerform(
-                                #selector(NSSplitViewController.toggleSidebar(_:)), with: nil
+        #if os(macOS)
+        WFNavigation(
```
Comment (AngeloStavrow) [inline Shared/Navigation/ContentView.swift:9]: We're essentially just wrapping these same views in our new WFNavigation view.

File: Shared/Navigation/WFNavigation.swift [hunk 3]
```diff
@@ -0,0 +1,37 @@
...
+        @ViewBuilder postDetail: () -> PostDetail
+    ) {
+        self.collectionList = collectionList()
+        self.postList = postList()
+        self.postDetail = postDetail()
+    }
+
+    var body: some View {
+        #if os(macOS)
+        NavigationSplitView {
```
Comment (AngeloStavrow) [inline Shared/Navigation/WFNavigation.swift:22]: Eventually we want to move the iOS app to use NavigationSplitView for iOS 16+

File: Shared/PostList/PostListView.swift [hunk 4]
```diff
@@ -126,18 +126,18 @@ struct PostListView: View {
             .frame(height: frameHeight)
             .background(Color(UIColor.systemGray5))
             .overlay(Divider(), alignment: .top)
-            .onReceive(NotificationCenter.default.publisher(for: UIApplication.didBecomeActiveNotification)) { _ in
```
Comment (AngeloStavrow) [inline Shared/PostList/PostListView.swift:129]: Every time the app becomes active, this notification would fire in iOS 17 and navigate us back to the Post list view. Moving it to an `onAppear` modifier below fixes this behaviour will maintaining the list-refresh intent.
